module.exports = {
  content: ["./src/components/**/*.tsx"],
  theme: {
    extend: {
      colors: {
        angel: "#439EFF",
        angelBlack: "#242237",
        angelBlackP5: "rgba(18, 71, 128, 0.05)",
        angelBlueP3: "rgba(18, 71, 128, 0.3)",
        angelRed: "#372226",
        angelRedP5: "rgba(128, 18, 51, 0.05)",
        angelRedM: "#ff434c",
        angelGrayC4: "#C4C4C4",
        angelGrayE2: "#E2E2E2",
        angelWhite: "#F6F6F6",
        angelYellowDark: "#B98C15",
        angelYellow: "#FECF56",
        angelBlueDark: "#3172B7",
        angelBlue: "#D7EAFF"
      },
      backgroundColor: {
        angel: "#439EFF",
        angelBlack: "#242237",
        angelBlackP5: "rgba(18, 71, 128, 0.05)",
        angelBlueP3: "rgba(18, 71, 128, 0.3)",
        angelRedP3: "rgba(128, 18, 18, 0.3)",
        angelRedM: "#ff434c",
        angelWhite: "#F6F6F6",
        angelYellowDark: "#B98C15",
        angelYellow: "#FECF56",
        angelBlueDark: "#3172B7",
        angelBlue: "#D7EAFF"
      },
      borderColor: {
        angel: "#439EFF",
        angelBlack: "#242237",
        angelBlackP5: "rgba(18, 71, 128, 0.05)",
        angelBlueP3: "rgba(18, 71, 128, 0.3)",
        angelRedP3: "rgba(128, 18, 18, 0.3)",
        angelRedM: "#ff434c",
      },
      textColor: {
        white: "#fff",
        angel: "#439EFF",
        angelBlack: "#242237",
        angelBlackP5: "rgba(18, 71, 128, 0.05)",
        angelBlueP3: "rgba(18, 71, 128, 0.3)",
        angelRed: "#372226",
        angelRedM: "#ff434c",
        angelRedP5: "rgba(128, 18, 51, 0.05)",
        angelGray: "#C2C2C2",
        angelYellow: "#B98C15"
      },
      fontFamily: {
        Poppins: ["Poppins", "sans-serif"],
        Arial: ["Arial", "sans-serif"],
        Helvetica: ["Helvetica", "sans-serif"],
        Baskerville: ["Baskerville", "serif"],
        TimesNewRoman: ["Times New Roman", "serif"],
        AkzidenzGrotesk: ["AkzidenzGrotesk", "sans-serif"],
        Gotham: ["Gotham", "sans-serif"],
        FranklinGothic: ["Franklin Gothic", "sans-serif"],
        Rockwell: ["Rockwell", "sans-serif"],
        Verdana: ["Verdana", "sans-serif"],
        Cambria: ["Cambria", "serif"],
        Garamond: ["Garamond", "serif"],
        Futura: ["Futura", "sans-serif"],
        Calibri: ["Calibri", "sans-serif"],
      },
    },
  },
  plugins: [],
  purge: ["./src/components/**/*.tsx"],
};
